Added ability to remove apps via PR. Using git to create/write on the…
weaveworks/weave-gitops pull request #1151
Opened 2021-12-01 01:03 UTC by josecordaz

… branch.

Closes: 

**What changed?**

**Why?**

**How did you test it?**

**Release notes**

**Documentation Changes**

2021-12-03 01:13 UTC, jpellizzari reviewed
The business logic code looks good, but I think we can improve the test code quite a bit. I will put something on the calendar for us to pair.

2021-12-03 21:49 UTC, josecordaz commented on test/integration/server/helpers/helpers.go
> +func NewGitlabClient(ctx context.Context, token string) *ghAPI.Client {
Actually, I'm not using it 🤔 , removing...

2021-12-06 21:13 UTC, luizbafilho requested changes
looks good, just a comment to improve tests maintainability

2021-12-07 13:04 UTC, luizbafilho approved these changes

2021-12-10 18:18 UTC, merged