1082 remove app
weaveworks/weave-gitops pull request #1174
Opened 2021-12-03 21:48 UTC by jpellizzari

Closes: 

**What changed?**

**Why?**

**How did you test it?**

**Release notes**

**Documentation Changes**

2021-12-04 00:04 UTC, jpellizzari commented
@joshri Please merge once this has been reviewed and :+1:

2021-12-06 23:05 UTC, joshri commented
I'm having a lot of problems removing my app on local - a 500 error doesn't stop the polling, and that error message isn't super helpful 😬 

![image](https://user-images.githubusercontent.com/65822698/144936625-afba3f58-8342-4c2c-be3c-c076b8e0d574.png)

2021-12-06 23:33 UTC, joshri requested changes

2021-12-06 23:33 UTC, joshri commented on ui/contexts/AppContext.tsx
> +    clearAsyncError();
💯 💯 💯 💯

2021-12-06 23:33 UTC, joshri commented on ui/pages/ApplicationRemove.tsx
> +    }
Should errors (other than 404) cancel the polling?

2021-12-06 23:33 UTC, joshri commented on ui/pages/ApplicationRemove.tsx
> +          <Alert title="Error" message={error?.message} />
This Alert needs `severity='error'`

2021-12-07 19:01 UTC, jpellizzari commented
@joshri would you kind making whatever changes are necessary to get this merged?

2021-12-07 19:55 UTC, joshri commented
> @joshri would you kind making whatever changes are necessary to get this merged?

A lot of my problems were due to having an old kind cluster with an old version of gitops installed...the good news is the core of it works - I'm making a couple bug issues for the rest! Now go back on vacation!!!

2021-12-07 19:57 UTC, joshri approved these changes

2021-12-08 15:45 UTC, merged

2021-12-09 14:19 UTC, sympatheticmoose commented
Just built from main, failing for me <img width="586" alt="Screenshot 2021-12-09 at 14 19 44" src="https://user-images.githubusercontent.com/19860021/145413363-4a5bc235-54af-49f0-bea8-8e7cb9047d71.png">