Extends Nav height to match Content
weaveworks/weave-gitops pull request #1279
Opened 2022-01-06 22:50 UTC by joshri

Closes: #1256 

Specifying the height of `<Main />` to be 100% allows `<NavContainer />` to extend through the whole page. Also had to change the background color to white <|:^}

Screenshot shows it extending past the Commits in App Detail - which is where it used to stop.

![image](https://user-images.githubusercontent.com/65822698/148463226-0c086a38-d450-4ad7-8201-a2e6139b816b.png)

2022-01-06 22:51 UTC, jpellizzari approved these changes

2022-01-07 15:34 UTC, sympatheticmoose requested changes
<img width="3360" alt="Screenshot 2022-01-07 at 15 31 32" src="https://user-images.githubusercontent.com/19860021/148567031-c212af63-3a6c-458b-8976-5831cd9c735d.png">
looks off to me...

2022-01-07 16:44 UTC, joshri commented
FIXED IT

![image](https://user-images.githubusercontent.com/65822698/148576859-64ca555b-692c-4c23-bc11-38d97dc599e7.png)

2022-01-10 10:28 UTC, sympatheticmoose commented
<img width="1606" alt="Screenshot 2022-01-10 at 10 27 08" src="https://user-images.githubusercontent.com/19860021/148751055-068eaad6-d8c0-4f09-b290-ed8a10f44c96.png">

There is no gap between the left menu and main panel on screen sizes less than 1680px in width

2022-01-14 11:29 UTC, sympatheticmoose approved these changes
LGTM - thanks Joshua

2022-01-14 15:28 UTC, merged