Jp support https
weaveworks/weave-gitops pull request #1331
Opened 2022-01-21 16:49 UTC by jpellizzari

Closes: 

**What changed?**

**Why?**

**How did you test it?**

**Release notes**

**Documentation Changes**

2022-01-25 11:33 UTC, bigkevmcd requested changes
As far as I can see this code doesn't work.

Since the changes to support cluster, it needs a significant rework to ensure that the cluster setup is authenticated.,

2022-01-25 11:33 UTC, bigkevmcd commented on cmd/gitops/install/cmd.go
> +			FluxHTTPSPassword: gitopsParams.FluxHTTPSPassword,
In my branch to address the conflicts, I had shifted this to passing in a `*flux.HTTPSCreds` rather than the two fields.

2022-01-25 11:33 UTC, bigkevmcd commented on pkg/services/automation/generator.go
> +		source, err = a.Flux.CreateSourceGit(app.Name, app.GitSourceURL, app.Branch, appSecretRef.String(), app.Namespace, nil)
I don't think this is correct?

2022-01-25 11:33 UTC, bigkevmcd commented on pkg/services/factory.go
> +	FluxHTTPSUsername string
See above for comment about using a `*flux.HTTPSCreds`

2022-01-25 11:33 UTC, bigkevmcd commented on pkg/services/factory.go
> +	// TODO: KEVIN!!!! Do we need to make these flux.HTTPSCreds?
I think this comment can come out now :-)

2022-01-25 11:33 UTC, bigkevmcd commented on pkg/services/gitops/install.go
> +	var creds *flux.HTTPSCreds
You could simplify this to just return nil if either string is empty, or the pointer if not.

See https://go.dev/doc/effective_go#control-structures for some guidance on this.

2022-01-26 16:05 UTC, jpellizzari commented
Closing per @JamWils

2022-01-26 16:05 UTC, closed without merging