fix: Weave GitOps username is hard-coded
weaveworks/weave-gitops pull request #2086
Opened 2022-05-04 09:58 UTC by yitsushi

Fixes #2001

2022-05-04 09:58 UTC, yitsushi commented
![image](https://user-images.githubusercontent.com/183191/166660929-450a1933-1bc0-46fd-b890-31e7f0b8597d.png)

2022-05-04 10:05 UTC, ozamosi requested changes
Changes to the chart will (just like documentation) be deployed straight to our end users. I believe this change would break all existing users, hence my change request.

Additionally, when you change the chart, you need to change the chart version, or the deploy becomes weird and we create 2 different "editions" of the same chart version.

2022-05-04 10:14 UTC, yitsushi commented
> Additionally, when you change the chart, you need to change the chart version, or the deploy becomes weird and we create 2 different "editions" of the same chart version.

I know that part, first I wanted some review if the approach is acceptable.

> Changes to the chart will (just like documentation) be deployed straight to our end users. I believe this change would break all existing users, hence my change request.

When the Helm Chart is applied, the RoleBinding will be changed. I don't see why would it break. If they log in with an `adminUser`, the username/password pair will not change, the underlying RoleBinding will change, but the change will just use the same value as defined in adminUser (the one they use to log in), the only requirement would be to restart the server pod, but that will happen because of the code (and with that the container image) changes.

2022-05-04 10:15 UTC, yitsushi commented
Tested workflow:
 - Used `main` while for `dev-cluster`
 - Log in as `dev/dev` and it shows `wego-admin`
 - Switched to this branch
 - Wait...
 - Log in as `dev/dev` and it shows `dev` and I see the same content

2022-05-04 10:16 UTC, ozamosi commented
> but that will happen because of the code (and with that the container image) changes.

No - merging this PR won't deploy core in any customer cluster. It will deploy the role binding. We can only do the chart change as part of a release.

2022-05-04 10:17 UTC, yitsushi commented
> No - merging this PR won't deploy core in any customer cluster. It will deploy the role binding. We can only do the chart change as part of a release.

That makes sense.

2022-05-04 10:18 UTC, Callisto13 commented
_dejavu_

I think this is something we (someone) does not want. It was a deliberate choice to have the k8s object User to always be called wego admin. I had a PR very similar to this a while ago (cannot find it anywhere) and was told that we do not want this. Basically the argument was that if we let it be configurable to this level, people can create any number of static users and we don't want to become an identity provider.
So basically, even though it feels "broken" to you and me, there is only ever one "user", regardless of what people think they are setting.

2022-05-04 10:19 UTC, yitsushi commented
Closing this PR based on the discussion above.

2022-05-04 10:21 UTC, Callisto13 commented
the fact that we keep having these discussions, because it looks to so weird to use and to implement, is... illuminating 😁

2022-05-04 10:25 UTC, Callisto13 commented
This is the closest thing to a "summary issue" i can find. It has all the links to various discussions around this. I may write it up fully so we have an easy link in future for when this inevitably comes up again

2022-05-04 10:29 UTC, ozamosi commented
> Unfortunately I can't split it up code and chart changes. At least I don't see how can I do that.

Add 2 users right now, and add a ticket to remove the old one after the next release, I suppose.

> for when this inevitably comes up again

Given this has been reported about one time for every person who's tried to use this, could we just fix it instead? "We don't want this" isn't accurate - _we_ clearly all do.

2022-05-04 10:35 UTC, Callisto13 commented
you'd have to take it up with @davidstauffer

2022-05-04 11:00 UTC, yitsushi commented
> Given this has been reported about one time for every person who's tried to use this, could we just fix it instead? "We don't want this" isn't accurate - _we_ clearly all do.

To be fair it's [kind of documented](https://docs.gitops.weave.works/docs/installation/#6-configure-password):
![image](https://user-images.githubusercontent.com/183191/166668891-a370b29f-e5aa-49b2-8bfe-c51268c595bc.png)

Maybe we just have to highlight the fact that the username + password pair is only for authentication, the logged in user will be `wego-admin`.

2022-05-04 13:47 UTC, yitsushi commented
> if we let it be configurable to this level, people can create any number of static users and we don't want to become an identity provider.

Technically with this approach they still can have only one user, because we read the user/pass from a single and hard-coded Secret, so no way they can create more than one user without changing the mechanism used to fetch auth credentials from Secret.

2022-05-04 14:28 UTC, JamWils commented
Alright, I think we should reopen this since it is a topic that keeps coming up.

1. Let's not break existing users so do what needs to be done.
2. The name can be configurable via helm chart values and it defaults to `wego-admin`.
3. This is the only role binding we provide in the chart.  This is effectively our one user.  We can't stop users from setting up more users then there already are, but that is on them.  They could do it now if they wanted to by uploading the correct yaml along side the `helm release`.

2022-05-04 15:39 UTC, yitsushi commented
Why the HelmChart test fails... updated the chart version :/

2022-05-04 15:57 UTC, ozamosi approved these changes
:tada: 

Not sure about the failed check - I added it, and it's clearly not doing what it should, so I need to debug it. I'm happy for you to ignore it and merge regardless.

2022-05-04 16:07 UTC, ozamosi commented
Fixed the chart check in #2094

2022-05-05 08:26 UTC, merged

2022-05-05 08:52 UTC, Callisto13 commented
> They could do it now if they wanted to by uploading the correct yaml along side the helm release.

Should we add something in docs (in another pr) that if ppl want to add more users, it is at their own risk and we are doing (will always do) the bare minimum when it comes to being an identity provider, and that they should def use oidc?