Add new profile 0.6.2 docs release notes
weaveworks/weave-gitops pull request #2828
Opened 2022-10-02 10:08 UTC by waleedhammam

Closes #182

**What changed?**
- Add policy profile v0.6.2 release notes changes

2022-10-02 10:31 UTC, alichaddad approved these changes

2022-10-05 11:28 UTC, serboctor approved these changes

2022-10-11 13:16 UTC, serboctor requested changes

2022-10-11 13:16 UTC, serboctor commented on website/docs/policy/releases.mdx
> +### Policy Library Compatibility
@waleedhammam let's change the compatability section to match this https://www.notion.so/weaveworks/Policy-Agent-v1-2-0-5709e5398bb44d52b387584344c4d0f5#e7f0785dc6b249dcbae5b7330a63a05b and add the same note below

2022-10-11 13:23 UTC, serboctor approved these changes

2022-10-11 14:52 UTC, serboctor approved these changes

2022-10-11 15:19 UTC, merged