add policy config documentations
weaveworks/weave-gitops pull request #2932
Opened 2022-10-26 11:45 UTC by waleedhammam

Closes #2929

**What changed?**

- add policy config documentations

2022-11-08 11:30 UTC, MostafaMegahid approved these changes

2022-11-08 13:19 UTC, serboctor requested changes

2022-11-08 13:19 UTC, serboctor commented on website/docs/policy/configuration.mdx
> +title: Weave policy configuration
```suggestion
title: Weave policy agent configuration
```

2022-11-08 13:19 UTC, serboctor commented on website/docs/policy/releases.mdx
> +sidebar_position: 6
releases should ideally be the last page

2022-11-08 13:41 UTC, serboctor approved these changes
LGTM

2022-11-10 14:47 UTC, serboctor commented on website/docs/policy/releases.mdx
> +  - add policy modes to labels to support filtering
```suggestion
  - Add policy modes to labels to support filtering
```

2022-11-10 14:48 UTC, serboctor commented on website/docs/policy/releases.mdx
> +  - support backward compatibility for policy version v2beta1
```suggestion
  - Support backward compatibility for policy version v2beta1
```

2022-11-10 14:48 UTC, serboctor approved these changes

2022-11-10 15:19 UTC, merged