add missing wge releases
weaveworks/weave-gitops pull request #3009
Opened 2022-11-15 16:35 UTC by ahsayde

Closes

**What changed?**
add releases `v0.10.1` and  `v0.10.2` to docs

**Why was this change made?**

**How was this change implemented?**

**How did you validate the change?**

**Release notes**

**Documentation Changes**

2022-11-15 16:44 UTC, serboctor requested changes
Minor capatalizations and changes

2022-11-15 16:44 UTC, serboctor commented on website/docs/enterprise/releases.mdx
> +- add missing support for policy version v2beta2 to tenancy cmd.
```suggestion
- Add missing support for policy version v2beta2 to tenancy cmd.
```

2022-11-15 16:44 UTC, serboctor commented on website/docs/enterprise/releases.mdx
> +- bump pipeline-controller
```suggestion
- Bump pipeline-controller
```

2022-11-15 16:44 UTC, serboctor commented on website/docs/enterprise/releases.mdx
> +- Adds support for showing policy modes and policy configs in the UI
```suggestion
- Add support for showing policy modes and policy configs in the UI 
```

2022-11-15 16:44 UTC, serboctor commented on website/docs/enterprise/releases.mdx
> +- Actually remove the watcher from the helm-watcher-cache
```suggestion
- Remove the watcher from the helm-watcher-cache
```

2022-11-15 16:44 UTC, serboctor commented on website/docs/enterprise/releases.mdx
> +- Adding edit capi cluster resource acceptance test
```suggestion
- Add edit capi cluster resource acceptance test
```

2022-11-15 17:19 UTC, foot approved these changes
🌟 Fantastic, thanks gang!

2022-11-16 09:11 UTC, serboctor approved these changes

2022-11-16 09:24 UTC, merged