Automate test case for 'wego add --url' flag
weaveworks/weave-gitops pull request #301
Opened 2021-06-09 21:50 UTC by rokshana-b

**What changed?**
- [ ] Added test case for `wego add app --url`
- [ ] Added `--branch` flag to `wego add app --dry-run` test case

**Why?**
To add test coverage for additional WeGO features

2021-06-09 21:52 UTC, josecordaz approved these changes
LGTM

2021-06-09 22:49 UTC, jrryjcksn approved these changes
LGTM. There's also a new app add mode (upstream helm repository) that we can only test with `--url`. So, this will be a good starting place for that too.

2021-06-10 00:41 UTC, iahmad9 commented on test/acceptance/test/add_tests.go
>  		url := "ssh://git@github.com/weaveworks-gitops-test/" + appRepoName + ".git"
Should not hardcode the org part, instead should fetch from os.Getenv("GITHUB_ORG") environment variable.

2021-06-10 00:41 UTC, iahmad9 commented on test/acceptance/test/add_tests.go
> +		url := "ssh://git@github.com/weaveworks-gitops-test/" + appRepoName + ".git"
Same as above => Should not hardcode the org part, instead should fetch from os.Getenv("GITHUB_ORG") environment variable.

2021-06-10 09:26 UTC, iahmad9 requested changes
Please change the hardcode GitHub org to env variable.

2021-06-10 18:20 UTC, merged