Added extraVolumes and extraVolumesMounts.
weaveworks/weave-gitops pull request #3143
Opened 2022-12-12 16:02 UTC by martin-adema

Closes

Added extraVolumes and extraVolumesMounts values to be able to mount extra volumes.

We use the Secret Store CSI Driver (https://secrets-store-csi-driver.sigs.k8s.io/introduction.html) to mount the OIDC client secret from Azure Keyvault.
To be able to use this driver a volume needs to be added to the deployment with reference to the driver and the SecretProviderClass.

**How was this change implemented?**

Change has been tested locallly with specifying the extraVolumes and extraVolumesMounts values and verifying the resulting deployment definition and tested with no value for extraVolumes and extraVolumesMounts.

**Release notes**

**Documentation Changes**

2022-12-12 16:25 UTC, makkes commented on charts/gitops-server/values.yaml
> +extraVolumeMounts: []
I believe it'd be convenient for users to provide examples for both of these settings to understand the syntax.

2022-12-14 13:04 UTC, makkes commented
lgtm but please squash the commits before we can merge.

2022-12-14 14:30 UTC, makkes approved these changes

2022-12-14 14:31 UTC, makkes requested changes
Sorry by squashing I mean locally squash all commits into one. We want this PR to be one commit.

2022-12-14 15:05 UTC, martin-adema commented
Sorry accidently merged from main. Fixed it and squashed the commits.

2022-12-14 15:07 UTC, makkes approved these changes

2022-12-21 10:01 UTC, merged