update policy agent v2.2.0 docs
weaveworks/weave-gitops pull request #3174
Opened 2022-12-20 11:50 UTC by ahsayde

Closes

**What changed?**
- update policy version v2.2.0 documents
- update policy agent profile new release

**Why was this change made?**
- to make docs up to date.

**How was this change implemented?**

**How did you validate the change?**

**Release notes**

**Documentation Changes**

2022-12-20 11:55 UTC, serboctor requested changes
We need to add it to the versioned docs as well so it appears on the live website.

2022-12-20 11:55 UTC, serboctor commented on website/docs/policy/releases.mdx
> +  - Add end-to-end tests.
I dont think we need to mention the tests in the public docs.

2022-12-20 12:12 UTC, waleedhammam approved these changes

2022-12-21 16:29 UTC, serboctor requested changes
LGTM...other than copying it to the versioned docs once they're ready, I've suggested a different phrasing for one of the sentences, and some punctuation-related  suggestion.

2022-12-21 16:29 UTC, serboctor commented on website/docs/workspaces/view-workspaces.mdx
> +In this view all the workspaces accross all clusters will be listed there. You can filter workspaces by its cluster or by its name.
```suggestion
This view lists workspaces across all clusters. You can filter workspaces by their clusters or their names.
```

2022-12-21 16:29 UTC, serboctor commented on website/docs/workspaces/view-workspaces.mdx
> +From the side menu. You can click on the **Workspaces** tab to go to the workspaces list view.
```suggestion
From the side menu, you can click on the **Workspaces** tab to go to the workspaces list view.
```

2022-12-22 10:21 UTC, serboctor approved these changes

2022-12-22 12:52 UTC, merged