Add icon and status for tf plans that are waiting for user action
weaveworks/weave-gitops pull request #3658
Opened 2023-04-28 13:34 UTC by joshri

Closes #2745

**What changed?**

**Why was this change made?**

**How was this change implemented?**

**How did you validate the change?**

**Release notes**

**Documentation Changes**

2023-05-01 05:56 UTC, chanwit requested changes
Thank you @joshri 
The change to the readCompute function makes sense to me.

There is an empty block which causes a lint error btw.

2023-05-01 05:56 UTC, chanwit commented on ui/components/KubeStatusIndicator.tsx
>      }
```suggestion
```

2023-05-03 11:17 UTC, chanwit commented
Orange icon! approved!
![image](https://user-images.githubusercontent.com/10666/235901502-9ca5a77b-a0a3-44cd-adca-fb9e86c308a6.png)

2023-05-03 11:18 UTC, chanwit approved these changes
LGTM

2023-05-03 11:18 UTC, opudrovs commented
Cool, thank you for testing it, @chanwit !

2023-05-03 13:02 UTC, merged