Fix log row which caused panic
weaveworks/weave-gitops pull request #4193
Opened 2024-02-15 14:34 UTC by marulkan

Closes

**What changed?**
Log line which cause panic

**Why was this change made?**
Bugfix

**How was this change implemented?**

**How did you validate the change?**
Implemented change in cluster where we had a helmchart which triggered this panic (old PSP cr).

**Release notes**

**Documentation Changes**

2024-11-14 19:52 UTC, casibbald commented
@marulkan Please can you provide more details on this fix

2025-01-03 20:37 UTC, erikgb commented
@casibbald I am pretty sure this PR is fixing a real issue. If you look at the signature of logr Logger function:

````go
func (l Logger) Error(err error, msg string, keysAndValues ...any)
````

The last variadic parameter needs to have a pair number arguments (key + value).

2025-01-03 20:38 UTC, erikgb commented on core/server/inventory.go
> +						logger.Error(err, "failed to determine if %s is namespace scoped", "entry", obj)
```suggestion
						logger.Error(err, "failed to determine if object is namespace scoped", "kind", obj.GetObjectKind().GroupVersionKind().Kind)
```

2025-01-03 20:43 UTC, erikgb requested changes
@marulkan Do you want to fix/rebase/squash this PR, or should I just do it? Please let me know!

2025-01-09 21:15 UTC, closed without merging