Make target to download binaries dependencies
weaveworks/weave-gitops pull request #43
Opened 2021-04-05 14:06 UTC by luizbafilho

I mostly brought the scripts from the wks repo.

2021-04-05 14:27 UTC, palemtnrider requested changes
Great to have the binaries downloaded dynamically.  I made a few minor comments.  Looks like the functions file came from WKP - I'd suggest removing the functions we don't need.

2021-04-05 14:27 UTC, palemtnrider commented on tools/download-deps.sh
> +	local special_tarpath_url
Nit formatting

2021-04-05 14:27 UTC, palemtnrider commented on tools/download-deps.sh
> +    echo $tarpath
Would it be helpful to print the other paths/urls?  Maybe print them inside the if statements below?

2021-04-05 14:27 UTC, palemtnrider commented on tools/download-deps.sh
> +        echo "No valid path for tool:" "${tool}"
Seems like we should exit here instead of trying to continue?

2021-04-05 14:27 UTC, palemtnrider commented on tools/download-deps.sh
> +tools=(flux)
Is this temporary for testing just the download of flux? I was thinking the list of tools to download would come directly from the dependencies.toml file. i.e., everything listed in there is downloaded.

2021-04-05 14:27 UTC, palemtnrider commented on tools/functions.sh
> +    mktemp -d 2>/dev/null || mktemp -d -t 'wk-quickstart'
Please replace wk-quickstart with something related to wego

2021-04-05 14:27 UTC, palemtnrider commented on tools/functions.sh
> +    local default_path="${HOME}/.wks/bin"
replace .wks with wego (and in the other places below)

2021-04-06 16:06 UTC, J-Thompson12 approved these changes
LGTM

2021-04-06 16:07 UTC, merged