Added yaml files for running wego-app in the cluster
weaveworks/weave-gitops pull request #715
Opened 2021-09-03 16:49 UTC by josecordaz

Closes: 

**What changed?**

**Why?**

**How did you test it?**

**Release notes**

**Documentation Changes**

2021-09-03 23:05 UTC, jpellizzari reviewed
Mostly minor feedback. @josecordaz for `uninstall`, could you either create a followup issue or, if you think it will be trivial, handle it here?

2021-09-04 00:17 UTC, josecordaz commented on manifests/manifests.go
> +	template, _ = template.Parse(string(deploymentTemplate))
that's what I thought initialy but after looking at the code of `template.Parse` it seems it can't return an error

2021-09-04 00:17 UTC, josecordaz commented on package.json
> +    "start": "npx parcel serve --port 4567 ui/index.html",
I'm not doing this, not sure what could be replacing that 🤔 I saw it on Luiz PR as well.

2021-09-04 00:20 UTC, josecordaz commented
> Mostly minor feedback. @josecordaz for `uninstall`, could you either create a followup issue or, if you think it will be trivial, handle it here?

I'll create an issue for this

2021-09-07 14:48 UTC, jpellizzari approved these changes

2021-09-07 14:48 UTC, jpellizzari commented on manifests/manifests.go
> +	template, _ = template.Parse(string(deploymentTemplate))
Is this the function you are using?: https://pkg.go.dev/text/template#Template.Parse

2021-09-07 14:49 UTC, jpellizzari commented on manifests/manifests_test.go
> +		var Deployment struct {
I think you can just use an `appsv1.Deployment` here

2021-09-07 14:50 UTC, jpellizzari commented on manifests/manifests_test.go
> +		Expect(Deployment.Spec.Template.Spec.Containers[0].Image).To(ContainSubstring(version.Version))
:tada: Much more specific. :+1:

2021-09-07 17:51 UTC, josecordaz commented on manifests/manifests.go
> +	template, _ = template.Parse(string(deploymentTemplate))
yes, it is 🙂

2021-09-09 13:01 UTC, luizbafilho requested changes
Looks good just some minor changes

2021-09-09 13:01 UTC, luizbafilho commented on pkg/kube/kubehttp.go
> +
I think your editor might be adding this

2021-09-09 19:46 UTC, luizbafilho approved these changes

2021-09-09 20:16 UTC, merged